name: deploy tags

on:
  push:
    tags: ["v*.*.*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PGP_PASSPHRASE }}
      - name: Cache Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: "zulu"
      - name: Build site and deploy maven registry
        env:
          GPG_KEYNAME: ${{ secrets.PGP_KEYNAME }}
          GPG_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          OSSRH_PWD_TOKEN: ${{ secrets.OSSRH_PWD_TOKEN }}
          OSSRH_USER_TOKEN: ${{ secrets.OSSRH_USER_TOKEN }}
        run: mvn -V -B --no-transfer-progress --settings .github/maven-settings.xml -P release clean deploy
